### ISSUE TITLE
game of zones hub 1 is stop at block 5390

### ISSUE THREAD

**Issue by iammelea** [cosmosdevs/GameOfZones#137]
```
E[2020-05-02|05:32:26.390] enterPrevote: ProposalBlock is invalid       module=consensus height=5391 round=101 err="wrong Block.Header.AppHash.  Expected E6C9BACD5B87599774EA6B1105AB6CAA01E538D5399FEA6D4624A637E448DCDE, got 05A191E9D77AB0B5F330670C643563D69D0440F7C96983DD44511F029E5BD3E9"
```
hub nodes stuck

**Comment by westaking** [comment]
`
$ curl http://35.233.155.199:26657/status


{
  "jsonrpc": "2.0",
  "id": -1,
  "result": {
    "node_info": {
      "protocol_version": {
        "p2p": "7",
        "block": "10",
        "app": "0"
      },
      "id": "ef71392a1658182a9207985807100bb3d106dce6",
      "listen_addr": "tcp://0.0.0.0:26656",
      "network": "gameofzoneshub-1",
      "version": "0.33.4",
      "channels": "4020212223303800",
      "moniker": "iqlusion",
      "other": {
        "tx_index": "on",
        "rpc_address": "tcp://0.0.0.0:26657"
      }
    },
    "sync_info": {
      "latest_block_hash": "A0C7B1160DB4398F95FF3AEA42DECADD67BDAE04E9D95E3183C4851772BE3EF5",
      "latest_app_hash": "9ABAC61A644F6B85FF580BF8249CAA620665EE00658B2F7120B4ED515EFD8F20",
      "latest_block_height": "5390",
      "latest_block_time": "2020-05-02T10:44:40.804776099Z",
      "earliest_block_hash": "693F41FBDE0F80D9A0592258C2DADBE5804900CACD9D286DCB65DEF3831DAEFA",
      "earliest_app_hash": "",
      "earliest_block_height": "1",
      "earliest_block_time": "2020-05-02T01:47:36.051130486Z",
      "catching_up": false
    },
    "validator_info": {
      "address": "8078FE73802A6F0582744D5BAA757DE7BB11FF22",
      "pub_key": {
        "type": "tendermint/PubKeyEd25519",
        "value": "v9dUD8EdB5nQP3jDofja0Q9ei7vKFqa9SLERfK+v9yQ="
      },
      "voting_power": "0"
    }
  }
`


yea me too.
So I can't make a relayer connection with gameofzonehub-1.

**vioting_power is 0.**
Did you stop the chain on purpose?

**Comment by iammelea** [comment]
vioting_power is 0. beacuse is one RPC endpoint not one validator.
